name: Scheduled Update

on:
  schedule:
    - cron: "0 3 * * 6"
  push:
    paths-ignore:
      - "**.md"
      - "**.yaml"
  pull_request:
  workflow_dispatch:

jobs:
  do-stuff-pretty-please:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4 

      - name: Login to image repository
        id: login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: |
            ghcr.io/${{ secrets.REGISTRY_USER }}/nvim-docker:latest
            ghcr.io/${{ secrets.REGISTRY_USER }}/nvim-docker:$(date +'%Y.%m.%d')
          labels: maintainer=${{ secrets.REGISTRY_USER }}
      
      - name: Build and push slim 
        id: pushslim
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ./Dockerfile.slim
          tags: |
            ghcr.io/${{ secrets.REGISTRY_USER }}/nvim-docker:slim
          labels: maintainer=${{ secrets.REGISTRY_USER }}
 
